export const ATTRIBUTES = [
  "Accuracy",
  "AP Recovery",
  "Constitution",
  "Critical Change",
  "Critical Modifier",
  "Damage",
  "Dodging",
  "Finesse",
  "Intelligence",
  "Magic Armor",
  "Magic Armor Max",
  "Magical Armor Max",
  "Magical Armor",
  "Memory",
  "Movement",
  "Physical Armor",
  "Resistances",
  "Start AP",
  "Strength",
  "Vitality",
  "Wits",
];

export const STATUS_EFFECTS = [
  "Acid",
  "Atrophy",
  "Bleeding",
  "Blessed",
  "Blinded",
  "Breathing Bubble",
  "Burning",
  "Charmed",
  "Clear-Minded",
  "Crippled",
  "Cursed",
  "Decaying",
  "Disarmed",
  "Diseased",
  "Enraged",
  "Evading",
  "Farsight",
  "Fortified",
  "Hasted",
  "Infected",
  "Infested",
  "Knocked Down",
  "Mad",
  "Madness",
  "Magic Shell",
  "Mending Metal",
  "Muted",
  "Permafrost",
  "Petrified",
  "Poisoned",
  "Regenerating",
  "Rested",
  "Shackles of Pain",
  "Shocked",
  "Silenced",
  "Skin Graft",
  "Sleeping",
  "Slowed",
  "Soothing Cold",
  "Soul Mate",
  "Steam Lance",
  "Stunned",
  "Suffocating",
  "Taunted",
  "Teleport",
  "Terrified",
];

export const SKILL_SCHOOLS = [
  "Aerotheurge",
  "Geomancer",
  "Huntsman",
  "Hydrosophist",
  "Necromancer",
  "Polymorph",
  "Pyrokinetic",
  "Scoundrel",
  "Summoning",
  "Warfare",
  "Sourcery",
  "Special",
];
