export const SKILL_SCHOOLS = [
  "Aerotheurge",
  "Geomancer",
  "Huntsman",
  "Hydrosophist",
  "Polymorph",
  "Pyrokinetic",
  "Summoning",
  "Warfare",
];

export const ATTRIBUTES = [
  "Accuracy",
  "AP Recovery",
  "Contitution",
  "Dodging",
  "Finesse",
  "Intelligence",
  "Magic Armor",
  "Magic Armor Max",
  "Magical Armor Max",
  "Magical Armor",
  "Memory",
  "Movement",
  "Physical Armor",
  "Resistances",
  "Start AP",
  "Strength",
  "Vitality",
  "Wits",
];

export const STATUS_EFFECTS = [
  "Acid",
  "Atrophy",
  "Bleeding",
  "Blessed",
  "Blinded",
  "Burning",
  "Charmed",
  "Clear-Minded",
  "Crippled",
  "Cursed",
  "Decaying",
  "Disarmed",
  "Diseased",
  "Enraged",
  "Evading",
  "Farsight",
  "Fortified",
  "Hasted",
  "Infested",
  "Knocked Down",
  "Mad",
  "Magic Shell",
  "Mending Metal",
  "Muted",
  "Permafrost",
  "Petrified",
  "Poisoned",
  "Regenerating",
  "Rested",
  "Shackles of Pain",
  "Shocked",
  "Skin Graft",
  "Sleeping",
  "Slowed",
  "Soothing Cold",
  "Soul Mate",
  "Steam Lance",
  "Stunned",
  "Taunted",
  "Teleport",
  "Terrified",
];
